version: '3.8'

services:
    php-fpm:
        build:
            context: ./docker-compose/php-fpm
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-php-fpm
        restart: unless-stopped
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - ./:/var/www
            - ./docker-compose/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
        networks:
            - backend

    web_server:
        image: nginx:1.19-alpine
        container_name: ${APP_NAME}-web
        restart: unless-stopped
        expose:
            - 80
        ports:
            - 80:80
        volumes:
            - ./:/var/www:delegated
            - ./docker-compose/logs/nginx:/var/log/nginx
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d:ro
            - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker-compose/nginx/sites-available/:/etc/nginx/sites-available:ro
        depends_on:
            - php-fpm
        networks:
            - backend
            - web
        working_dir: /var/www
        command: [nginx-debug, '-g', 'daemon off;']

networks:
    web:
        driver: bridge
    backend:
        driver: bridge
