<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtM8OEX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtM8OEX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUtM8OEX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUtM8OEX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUtM8OEX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UtM8OEX',
    'container.build_id' => 'd6c3b6ee',
    'container.build_time' => 1618577889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtM8OEX');
